server:
  port: 6001

spring:
  application:
    name: microservice-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka9002.com:9002/eureka/,http://eureka9001.com:9001/eureka/
  instance:
    instance-id: microservice-zuul6001                        #自定义服务名称信息
    prefer-ip-address: true                                   #访问路径可以显示IP地址

info:
  app.name: microservice-zuul
  company.name: www.lzj.com
  build.artifactId: microservice-zuul
  build.version: 1.0-SNAPSHOT

zuul:
  prefix: /MyDemo
  ignored-services: microservice-provider
  routes:
    mydept.serviceId: microservice-provider
    mydept.path: /provider/**
