server:
  port: 7001

feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/
