server:
  port: 8002

spring:
  application:
    name: microservice-hibernate-provider1                       #微服务的名字
  datasource:
    driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource              # 当前数据源操作类型
    url: "jdbc:mysql://localhost:3306/myspringcloud?characterEncoding=UTF8"                   # 数据库名称
    username: root
    password: root
    #下面为连接池的补充设置，应用到上面所有数据源中
    #初始化大小，最小，最大
    initialSize: 3
    minIdle: 3
    maxActive: 30
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

hibernate:
  jpa:
    format_sql: true
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


eureka:
  client:
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/
  instance:
    instance-id: microservice-hibernate-provider1


#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#      password: root
#      driverClassName: com.mysql.jdbc.Driver
#    jpa:
#      database: MYSQL
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL5Dialect
#
